server:
  port: 8001 #访问端口号

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/ #注册到其他server，可以注册到多个server，通过逗号分隔


spring:
  application:
    name: server1 #注册到eureka的服务名，多个client取相同的服务名可以组成集群，轮巡调用集群的端口实现负载均衡