server:
  port: 9011
logging:
  level:
    com.github.brick.action.flow: debug


action-flow:
  security:
    enable: true
  storage:
    type: memory
  datasource:
    driver: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}





spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: root

